// GENERATED by scripts/build_landing_assets.py from scripts/landing_assets.json. Do not edit by hand: change the list and run
// the script (python scripts/build_landing_assets.py --src <folder of rendered pictures>).
//
// Every picture of the landing page has a content hash in its name (public/assets/landing/<dir>/<name>.<hash>.webp), so
// vercel.json serves it with "Cache-Control: immutable" for a year; a changed picture is another address. This file is the
// only place that knows the addresses: components ask for a name and get the address, the srcset and the size.
//
//   asset('m/lounge_acrylic__eye__tight')     the family: every width as a srcset, one of them as src (pick, default 900)
//   asset('reveal/gd_iris_900')               one file
//   asset('m/study_acrylic_3x2__eye__wide', 2000)  the family with the 2000 px file as the src
//   asset('m/lounge_acrylic__eye__tight', { max: 1200 })   the family without its widest files
// A name that is not here does not compile. The structures that name pictures (wall, gallery, rooms, Reveal) are in
// ./assets.data.ts, which only the sections below the first screen load.

export const ASSET_BASE = '/assets/landing/';

/** name (folder and file name without the extension) -> [content hash, width, height, bytes] */
const FILES = {
  'art/clean_br_480': ['c3e2b2ea95', 480, 480, 14002],
  'art/clean_br_900': ['f0f4248f19', 900, 900, 37640],
  'art/clean_gr_480': ['b5cb554769', 480, 480, 12812],
  'art/clean_gr_900': ['9206cb13a8', 900, 900, 30104],
  'art/clean_own_480': ['08b9d35fa4', 480, 480, 11748],
  'art/clean_own_900': ['edbcbbf238', 900, 900, 28554],
  'art/clean_yg_480': ['0669c28bb6', 480, 480, 12942],
  'art/clean_yg_900': ['4ff7ba018c', 900, 900, 31194],
  'art/dot_br_64': ['cbf4413dc8', 64, 64, 1076],
  'art/dot_gr_64': ['f05426eb17', 64, 64, 1168],
  'art/dot_own_64': ['e1bb690f1b', 64, 64, 1224],
  'art/dot_yg_64': ['41adc7390e', 64, 64, 1178],
  'art/duo_clean_by_480': ['5b64181211', 480, 320, 11074],
  'art/duo_clean_by_900': ['55b51c8389', 900, 600, 30626],
  'art/duo_infinity_bb_480': ['7ccf7fc6e3', 480, 320, 15344],
  'art/duo_infinity_bb_900': ['3f12084cbb', 900, 600, 51316],
  'art/duo_infinity_by_480': ['14cf42ddd7', 480, 320, 16264],
  'art/duo_infinity_by_900': ['b87989201f', 900, 600, 51826],
  'art/duo_kiss_bb_480': ['30f216fa1e', 480, 320, 15070],
  'art/duo_kiss_bb_900': ['daced74f55', 900, 600, 48844],
  'art/fam_4_480': ['22389b4c22', 480, 320, 17088],
  'art/fam_4_900': ['61d5f1cf08', 900, 600, 57474],
  'art/fam_5_480': ['7210489a6f', 480, 320, 18756],
  'art/fam_5_900': ['4659b697da', 900, 600, 64408],
  'art/fam_6_480': ['7de12d6671', 480, 320, 19974],
  'art/fam_6_900': ['e38b0d5f60', 900, 600, 67010],
  'art/fam_trio_480': ['9be32b883d', 480, 480, 26956],
  'art/fam_trio_900': ['1e0242059e', 900, 900, 83924],
  'art/fibre_crop_1200': ['43b3f724ac', 1200, 1200, 55698],
  'art/fibre_full_480': ['97cd852736', 480, 480, 19024],
  'art/gold_br_480': ['aa5f8cc1d4', 480, 480, 21974],
  'art/gold_br_900': ['2b39ad48cb', 900, 900, 56860],
  'art/gold_gr_480': ['74ab07fc67', 480, 480, 20700],
  'art/gold_gr_900': ['4768520c48', 900, 900, 50870],
  'art/gold_own_480': ['30bf0c01d0', 480, 480, 20642],
  'art/gold_own_900': ['1cbe8238ab', 900, 900, 51020],
  'art/gold_yg_480': ['bf64749c08', 480, 480, 21744],
  'art/gold_yg_900': ['5326d6aa2d', 900, 900, 53968],
  'art/powder_br_480': ['c10108b8b2', 480, 480, 29880],
  'art/powder_br_900': ['db26aa96e2', 900, 900, 98684],
  'art/powder_gr_480': ['8e8c00c06c', 480, 480, 27782],
  'art/powder_gr_900': ['a9ad3fe6a9', 900, 900, 84066],
  'art/powder_own_480': ['71687e6105', 480, 480, 30706],
  'art/powder_own_900': ['75930f7c5c', 900, 900, 95482],
  'art/powder_yg_480': ['84be4b89be', 480, 480, 31984],
  'art/powder_yg_900': ['a9bbb50b70', 900, 900, 99844],
  'art/radiance_br_480': ['291966931b', 480, 480, 16182],
  'art/radiance_br_900': ['17c84f8dd1', 900, 900, 42968],
  'art/radiance_gd_900': ['5ce908d3d6', 900, 900, 38858],
  'art/radiance_gr_480': ['c8d7b6f04f', 480, 480, 16106],
  'art/radiance_gr_900': ['5ce908d3d6', 900, 900, 38858],
  'art/radiance_own_480': ['55aeed849f', 480, 480, 16760],
  'art/radiance_own_900': ['4475d3548f', 900, 900, 41994],
  'art/radiance_yg_480': ['1e1c150ab0', 480, 480, 17370],
  'art/radiance_yg_900': ['9a3085f203', 900, 900, 42692],
  'art/splash_br_480': ['e69a00db27', 480, 480, 26480],
  'art/splash_br_900': ['e8023b62c2', 900, 900, 74788],
  'art/splash_gr_480': ['2c16f660df', 480, 480, 19286],
  'art/splash_gr_900': ['60e3a8fba0', 900, 900, 48910],
  'art/splash_own_480': ['466d1ca298', 480, 480, 20312],
  'art/splash_own_900': ['2b445e7a07', 900, 900, 51402],
  'art/splash_yg_480': ['74af76e29f', 480, 480, 17648],
  'art/splash_yg_900': ['45783160e0', 900, 900, 42984],
  'art/universe_br_480': ['6d27e7b9ea', 480, 480, 17458],
  'art/universe_br_900': ['71788b86cc', 900, 900, 48346],
  'art/universe_gr_480': ['be75eaa5c3', 480, 480, 30032],
  'art/universe_gr_900': ['70f7d4c9ac', 900, 900, 76264],
  'art/universe_own_480': ['e58dc6d212', 480, 480, 29722],
  'art/universe_own_900': ['861a20d1b5', 900, 900, 77494],
  'art/universe_yg_480': ['9e6eae4505', 480, 480, 35306],
  'art/universe_yg_900': ['6556c01c62', 900, 900, 92698],
  'art/wallthumb_collision_96': ['78d47392f6', 96, 96, 2108],
  'art/wallthumb_eye_96': ['10241ffc40', 96, 96, 1638],
  'art/wallthumb_family4_96': ['65aa0dee2d', 96, 96, 1160],
  'art/wallthumb_universe_96': ['cc82f33ca2', 96, 96, 2744],
  'm/cafe_acrylic_3x2__collision__tight_1200': ['75569e42ad', 1200, 800, 75932],
  'm/cafe_acrylic_3x2__collision__tight_600': ['6134659e89', 600, 400, 23636],
  'm/desk_block__eye__tight_1200': ['f7b25d8364', 1200, 1499, 71030],
  'm/desk_block__eye__tight_600': ['63fc48fe37', 600, 750, 27530],
  'm/desk_block__family4__tight_1200': ['e2bc1454e2', 1200, 1499, 74876],
  'm/desk_block__family4__tight_600': ['c5430050da', 600, 750, 27294],
  'm/desk_block__universe__tight_1200': ['7a0714d714', 1200, 1499, 87852],
  'm/desk_block__universe__tight_600': ['62b553d211', 600, 750, 33372],
  'm/gallery_acrylic_oblique__collision__tight_1200': ['c50d9e6fa2', 1200, 800, 45090],
  'm/gallery_acrylic_oblique__collision__tight_600': ['7dcece54da', 600, 400, 14430],
  'm/gallery_framed_3x2__family4__tight_1200': ['5a420f5c26', 1200, 800, 30810],
  'm/gallery_framed_3x2__family4__tight_600': ['d78b03daa8', 600, 400, 9206],
  'm/hall_canvas_3x2__collision__tall_1200': ['0184154c4c', 1200, 1500, 64334],
  'm/hall_canvas_3x2__collision__tall_600': ['ec3af09cbc', 600, 750, 17516],
  'm/hall_canvas_3x2__family4__tall_1200': ['a0fe1a7436', 1200, 1500, 64968],
  'm/hall_canvas_3x2__family4__tall_600': ['d02f73bbf5', 600, 750, 17742],
  'm/hall_canvas__eye__tight_1200': ['9889fbaf76', 1200, 1500, 87612],
  'm/hall_canvas__eye__tight_600': ['ea13d9d8db', 600, 750, 24364],
  'm/hall_canvas__universe__tight_1200': ['1baed7be72', 1200, 1500, 97030],
  'm/hall_canvas__universe__tight_600': ['e76b8938b6', 600, 750, 27648],
  'm/hands_acrylic__eye__tight_1200': ['e9d9ed5c5c', 1200, 1500, 86852],
  'm/hands_acrylic__eye__tight_600': ['2796b4f4a3', 600, 750, 36000],
  'm/hotel_framed_3x2__collision__tall_1200': ['6a6ff8b1c4', 1200, 1500, 128742],
  'm/hotel_framed_3x2__collision__tall_600': ['8e612d40d2', 600, 750, 26064],
  'm/hotel_framed_3x2__family4__tall_1200': ['54d1be3dee', 1200, 1500, 128794],
  'm/hotel_framed_3x2__family4__tall_600': ['19550800e4', 600, 750, 26414],
  'm/hotel_framed__eye__tight_1200': ['d6255e1fcd', 1200, 1500, 65502],
  'm/hotel_framed__eye__tight_600': ['ff469a7a87', 600, 750, 15168],
  'm/hotel_framed__universe__tight_1200': ['a311f897d4', 1200, 1500, 74078],
  'm/hotel_framed__universe__tight_600': ['d196619888', 600, 750, 18226],
  'm/living_acrylic_3x2__collision__tall_1200': ['ae82aa89d0', 1200, 1500, 55950],
  'm/living_acrylic_3x2__collision__tall_600': ['223fdcb8dc', 600, 750, 15074],
  'm/living_acrylic_3x2__collision__tight_1200': ['787f1c755e', 1200, 800, 33030],
  'm/living_acrylic_3x2__collision__tight_600': ['571909e5f9', 600, 400, 9922],
  'm/living_acrylic_3x2__family4__tall_1200': ['eb80061ff4', 1200, 1500, 57016],
  'm/living_acrylic_3x2__family4__tall_600': ['1c66a22280', 600, 750, 15050],
  'm/living_acrylic__eye__sq_600': ['bb89dc22d9', 600, 600, 10044],
  'm/living_acrylic__eye__sq_900': ['bbd84b9b92', 900, 900, 19342],
  'm/living_acrylic__eye__tight_1200': ['f9bfcfc1cc', 1200, 1500, 93160],
  'm/living_acrylic__eye__tight_600': ['15ce9d48a2', 600, 750, 22286],
  'm/living_acrylic__universe__sq_600': ['6bdb7c7d19', 600, 600, 16076],
  'm/living_acrylic__universe__sq_900': ['fd34c00964', 900, 900, 29914],
  'm/living_acrylic__universe__tight_1200': ['23d7662199', 1200, 1500, 103946],
  'm/living_acrylic__universe__tight_600': ['af063a3a6f', 600, 750, 26114],
  'm/lounge_acrylic__eye__tight_1200': ['80e3a982fe', 1200, 1500, 37736],
  'm/lounge_acrylic__eye__tight_600': ['835cc784a5', 600, 750, 17318],
  'm/lounge_acrylic__eye__tight_900': ['9a14aa8d5f', 900, 1125, 34972],
  'm/macro_acrylic_corner__universe__wide_1200': ['7e61240a98', 1200, 805, 30520],
  'm/macro_acrylic_corner__universe__wide_2000': ['4e402ec7ff', 2000, 1342, 60668],
  'm/macro_acrylic_corner__universe__wide_600': ['58a7a48367', 600, 403, 11846],
  'm/office_metal_3x2__collision__tall_1200': ['ab5a8a0d60', 1200, 1500, 48282],
  'm/office_metal_3x2__collision__tall_600': ['63b456c51d', 600, 750, 14672],
  'm/office_metal_3x2__family4__tall_1200': ['034f866389', 1200, 1500, 49074],
  'm/office_metal_3x2__family4__tall_600': ['5d986d1b5e', 600, 750, 14430],
  'm/office_metal__eye__tight_1200': ['8506b1a4cf', 1200, 1500, 30934],
  'm/office_metal__eye__tight_600': ['a2c1c4b240', 600, 750, 9996],
  'm/office_metal__universe__tight_1200': ['3dac9231d1', 1200, 1500, 40274],
  'm/office_metal__universe__tight_600': ['4e2a3c3bc0', 600, 750, 13634],
  'm/phone_desk__collision__wide_1200': ['f9ff29c51c', 1200, 1490, 86428],
  'm/phone_desk__collision__wide_1856': ['3a19798546', 1856, 2304, 173244],
  'm/phone_desk__collision__wide_600': ['7884c0e5c4', 600, 745, 31902],
  'm/phone_desk__eye__wide_1200': ['2b23288868', 1200, 1490, 87256],
  'm/phone_desk__eye__wide_1856': ['6371310292', 1856, 2304, 174620],
  'm/phone_desk__eye__wide_600': ['98fe539ac9', 600, 745, 32364],
  'm/phone_desk__family4__wide_1200': ['e4e487ebb3', 1200, 1490, 87112],
  'm/phone_desk__family4__wide_1856': ['a0a8f187d9', 1856, 2304, 174722],
  'm/phone_desk__family4__wide_600': ['7ac948176b', 600, 745, 32140],
  'm/phone_desk__universe__wide_1200': ['4adef118bd', 1200, 1490, 94946],
  'm/phone_desk__universe__wide_1856': ['30ac62b495', 1856, 2304, 186334],
  'm/phone_desk__universe__wide_600': ['4f4a695372', 600, 745, 34458],
  'm/shelf_acrylic_30__eye__tight_600': ['f41cece0e6', 600, 751, 16428],
  'm/shelf_acrylic_30__eye__tight_881': ['c5be354365', 881, 1102, 37916],
  'm/study_acrylic_3x2__eye__wide_1200': ['c69343a965', 1200, 805, 39132],
  'm/study_acrylic_3x2__eye__wide_2000': ['8fc001f382', 2000, 1342, 80652],
  'm/study_acrylic_3x2__eye__wide_600': ['5cff7d082a', 600, 403, 14916],
  'reveal/disc_own_420': ['03cc37b24d', 420, 420, 13790],
  'reveal/gd_iris_1200': ['de76750d8f', 1200, 1200, 44918],
  'reveal/gd_iris_900': ['bf686d6084', 900, 900, 31966],
  'reveal/gd_photo_1200': ['7ffbe423ec', 1200, 1200, 46912],
  'reveal/gd_photo_900': ['b220424270', 900, 900, 33510],
  'reveal/own_iris_1200': ['8d2d4ea10b', 1200, 1200, 60480],
  'reveal/own_iris_900': ['10a1f28561', 900, 900, 42908],
  'reveal/own_photo_1200': ['223e7344d1', 1200, 1200, 32944],
  'reveal/own_photo_900': ['1e639a177d', 900, 900, 23992],
  'ui/before-phone-crop-315': ['992b984c9f', 315, 315, 13726],
  'ui/preview_wm_360': ['b110867a99', 360, 360, 18260],
} as const satisfies Record<string, readonly [string, number, number, number]>;

/** family (the name without _<width>) -> the widths that exist, ascending */
const WIDTHS = {
  'art/clean_br': [480, 900],
  'art/clean_gr': [480, 900],
  'art/clean_own': [480, 900],
  'art/clean_yg': [480, 900],
  'art/dot_br': [64],
  'art/dot_gr': [64],
  'art/dot_own': [64],
  'art/dot_yg': [64],
  'art/duo_clean_by': [480, 900],
  'art/duo_infinity_bb': [480, 900],
  'art/duo_infinity_by': [480, 900],
  'art/duo_kiss_bb': [480, 900],
  'art/fam_4': [480, 900],
  'art/fam_5': [480, 900],
  'art/fam_6': [480, 900],
  'art/fam_trio': [480, 900],
  'art/fibre_crop': [1200],
  'art/fibre_full': [480],
  'art/gold_br': [480, 900],
  'art/gold_gr': [480, 900],
  'art/gold_own': [480, 900],
  'art/gold_yg': [480, 900],
  'art/powder_br': [480, 900],
  'art/powder_gr': [480, 900],
  'art/powder_own': [480, 900],
  'art/powder_yg': [480, 900],
  'art/radiance_br': [480, 900],
  'art/radiance_gd': [900],
  'art/radiance_gr': [480, 900],
  'art/radiance_own': [480, 900],
  'art/radiance_yg': [480, 900],
  'art/splash_br': [480, 900],
  'art/splash_gr': [480, 900],
  'art/splash_own': [480, 900],
  'art/splash_yg': [480, 900],
  'art/universe_br': [480, 900],
  'art/universe_gr': [480, 900],
  'art/universe_own': [480, 900],
  'art/universe_yg': [480, 900],
  'art/wallthumb_collision': [96],
  'art/wallthumb_eye': [96],
  'art/wallthumb_family4': [96],
  'art/wallthumb_universe': [96],
  'm/cafe_acrylic_3x2__collision__tight': [600, 1200],
  'm/desk_block__eye__tight': [600, 1200],
  'm/desk_block__family4__tight': [600, 1200],
  'm/desk_block__universe__tight': [600, 1200],
  'm/gallery_acrylic_oblique__collision__tight': [600, 1200],
  'm/gallery_framed_3x2__family4__tight': [600, 1200],
  'm/hall_canvas_3x2__collision__tall': [600, 1200],
  'm/hall_canvas_3x2__family4__tall': [600, 1200],
  'm/hall_canvas__eye__tight': [600, 1200],
  'm/hall_canvas__universe__tight': [600, 1200],
  'm/hands_acrylic__eye__tight': [600, 1200],
  'm/hotel_framed_3x2__collision__tall': [600, 1200],
  'm/hotel_framed_3x2__family4__tall': [600, 1200],
  'm/hotel_framed__eye__tight': [600, 1200],
  'm/hotel_framed__universe__tight': [600, 1200],
  'm/living_acrylic_3x2__collision__tall': [600, 1200],
  'm/living_acrylic_3x2__collision__tight': [600, 1200],
  'm/living_acrylic_3x2__family4__tall': [600, 1200],
  'm/living_acrylic__eye__sq': [600, 900],
  'm/living_acrylic__eye__tight': [600, 1200],
  'm/living_acrylic__universe__sq': [600, 900],
  'm/living_acrylic__universe__tight': [600, 1200],
  'm/lounge_acrylic__eye__tight': [600, 900, 1200],
  'm/macro_acrylic_corner__universe__wide': [600, 1200, 2000],
  'm/office_metal_3x2__collision__tall': [600, 1200],
  'm/office_metal_3x2__family4__tall': [600, 1200],
  'm/office_metal__eye__tight': [600, 1200],
  'm/office_metal__universe__tight': [600, 1200],
  'm/phone_desk__collision__wide': [600, 1200, 1856],
  'm/phone_desk__eye__wide': [600, 1200, 1856],
  'm/phone_desk__family4__wide': [600, 1200, 1856],
  'm/phone_desk__universe__wide': [600, 1200, 1856],
  'm/shelf_acrylic_30__eye__tight': [600, 881],
  'm/study_acrylic_3x2__eye__wide': [600, 1200, 2000],
  'reveal/disc_own': [420],
  'reveal/gd_iris': [900, 1200],
  'reveal/gd_photo': [900, 1200],
  'reveal/own_iris': [900, 1200],
  'reveal/own_photo': [900, 1200],
  'ui/preview_wm': [360],
} as const satisfies Record<string, readonly number[]>;

export type AssetFile = keyof typeof FILES;
export type AssetFamily = keyof typeof WIDTHS;
export type AssetName = AssetFile | AssetFamily;

/** What a picture needs: the address, the srcset of a family with several widths, the size of the src (every width of a
 *  family has the same shape, so width and height reserve the right space). Same shape as PictureAsset in ./ui.tsx. */
export interface PictureAsset { src: string; srcset?: string; w: number; h: number }

/** The address of one file. */
export function assetUrl(file: AssetFile): string {
  const slash = file.lastIndexOf('/');
  return `${ASSET_BASE}${file.slice(0, slash + 1)}${file.slice(slash + 1)}.${FILES[file][0]}.webp`;
}

/** The widths a family has, ascending. */
export function assetWidths(family: AssetFamily): readonly number[] {
  return WIDTHS[family];
}

/** How a family becomes a srcset: pick = the width whose file is the src (nearest to it, default 900); max = the widest file the
 *  srcset offers (the first screen offers 600, 900 and 1200 only, so a phone with a dense screen does not fetch the 2000 px file). */
export type AssetOptions = number | { pick?: number; max?: number };

/** A file by name, or a family as a srcset. */
export function asset(name: AssetName, options: AssetOptions = {}): PictureAsset {
  if (name in FILES) {
    const f = name as AssetFile;
    return { src: assetUrl(f), w: FILES[f][1], h: FILES[f][2] };
  }
  const o = typeof options === 'number' ? { pick: options } : options;
  const pick = o.pick ?? 900;
  const all = WIDTHS[name as AssetFamily];
  const ws = all.filter((w) => w <= (o.max ?? Infinity));
  if (ws.length === 0) throw new Error(`asset ${name}: no file up to ${o.max} px`);
  let best: number = ws[0];
  for (const w of ws) if (Math.abs(w - pick) < Math.abs(best - pick)) best = w;
  const file = (w: number) => `${name}_${w}` as AssetFile;
  return {
    src: assetUrl(file(best)),
    srcset: ws.length > 1 ? ws.map((w) => `${assetUrl(file(w))} ${w}w`).join(', ') : undefined,
    w: FILES[file(best)][1],
    h: FILES[file(best)][2],
  };
}

/** Every address of the manifest (the build's check and the service of the preload list read it). */
export const ALL_ASSET_FILES = Object.keys(FILES) as AssetFile[];
export const ASSET_HASH = FILES as Readonly<Record<AssetFile, readonly [string, number, number, number]>>;
