// GENERATED by scripts/build_landing_assets.py from scripts/landing_assets.json. Do not edit by hand.
//
// What the sections below the first screen need to know about the pictures: which family is which wall scene (material x
// artwork), which flat artworks the gallery shows, the rooms of "More ways to see it", the Reveal's layers, the wall
// thumbnails and the close-up crop. Every name is checked against the manifest (./assets.ts) by the compiler. No price and
// no text is here: the words are the copy's (src/landing/copy), the prices come from src/landing/prices.ts.
import type { AssetFamily, AssetFile } from './assets';

export type Material = 'acrylic' | 'metal' | 'canvas' | 'framed' | 'block' | 'phone';
export type WallArt = 'eye' | 'universe' | 'family4' | 'collision';
export type EyeId = 'own' | 'yg' | 'br' | 'gr';
export type GalleryGroup = 'one' | 'two' | 'family';

/** The wall stage: the scene of a material with an artwork in it. sizeOk: the drawn size was estimated at 40 to 55 cm, so
 *  the page may print "about 50 cm" next to it. de: the German version of the scene (the phone shows text). */
export interface StageScene { base: AssetFamily; sizeOk: boolean; de?: AssetFamily }
export const STAGE: Readonly<Record<Material, Readonly<Partial<Record<WallArt, StageScene>>>>> = {
  "acrylic": {
    "eye": {
      "base": "m/lounge_acrylic__eye__tight",
      "sizeOk": true
    },
    "universe": {
      "base": "m/lounge_acrylic__universe__tight",
      "sizeOk": true
    },
    "family4": {
      "base": "m/lounge_acrylic__family4__tight",
      "sizeOk": true
    },
    "collision": {
      "base": "m/lounge_acrylic_3x2__collision__tall",
      "sizeOk": false
    }
  },
  "metal": {
    "eye": {
      "base": "m/dining_metal__eye__tight",
      "sizeOk": true
    },
    "universe": {
      "base": "m/dining_metal__universe__tight",
      "sizeOk": true
    },
    "family4": {
      "base": "m/dining_metal__family4__tight",
      "sizeOk": true
    },
    "collision": {
      "base": "m/lounge_metal_3x2__collision__tall",
      "sizeOk": false
    }
  },
  "canvas": {
    "eye": {
      "base": "m/living_canvas__eye__tight",
      "sizeOk": true
    },
    "universe": {
      "base": "m/living_canvas__universe__tight",
      "sizeOk": true
    },
    "family4": {
      "base": "m/living_canvas__family4__tight",
      "sizeOk": true
    },
    "collision": {
      "base": "m/lounge_canvas_3x2__collision__tall",
      "sizeOk": false
    }
  },
  "framed": {
    "eye": {
      "base": "m/lounge_framed__eye__tight",
      "sizeOk": true
    },
    "universe": {
      "base": "m/lounge_framed__universe__tight",
      "sizeOk": true
    },
    "family4": {
      "base": "m/lounge_framed__family4__tight",
      "sizeOk": true
    },
    "collision": {
      "base": "m/lounge_framed_3x2__collision__tall",
      "sizeOk": false
    }
  },
  "block": {
    "eye": {
      "base": "m/desk_block__eye__tight",
      "sizeOk": false
    },
    "universe": {
      "base": "m/desk_block__universe__tight",
      "sizeOk": false
    },
    "family4": {
      "base": "m/desk_block__family4__tight",
      "sizeOk": false
    }
  },
  "phone": {
    "eye": {
      "base": "m/phone_desk__eye__wide",
      "sizeOk": false,
      "de": "m/phone_desk__eye_de__wide"
    },
    "universe": {
      "base": "m/phone_desk__universe__wide",
      "sizeOk": false
    },
    "family4": {
      "base": "m/phone_desk__family4__wide",
      "sizeOk": false
    },
    "collision": {
      "base": "m/phone_desk__collision__wide",
      "sizeOk": false
    }
  }
};

/** A tile of the style gallery. design: a single-eye style, its flat art is art/<design>_<eye> (two widths); file: a two-eye
 *  or family artwork, art/<file> (two widths). wallOwn / wall: the tile shown on the wall (Mantas's eye, or a fixed scene).
 *  engine: the style id of api/_lib/iris.py that makes it, null while the engine has none of that name. */
export interface GalleryTile {
  id: string;
  design?: string;
  file?: string;
  price: 'art' | 'black' | 'two' | 'n';
  src?: 'mixed';
  n?: number;
  square?: boolean;
  engine: string | null;
  wallOwn?: { base: AssetFamily; ratio: string };
  wall?: { base: AssetFamily; ratio: string };
}
export const GALLERY: {
  readonly groups: readonly GalleryGroup[];
  readonly eyes: readonly { id: EyeId; thumb: AssetFile }[];
  readonly one: readonly GalleryTile[];
  readonly two: readonly GalleryTile[];
  readonly family: readonly GalleryTile[];
} = {
  "groups": [
    "one",
    "two",
    "family"
  ],
  "eyes": [
    {
      "id": "own",
      "thumb": "art/dot_own_64"
    },
    {
      "id": "yg",
      "thumb": "art/dot_yg_64"
    },
    {
      "id": "br",
      "thumb": "art/dot_br_64"
    },
    {
      "id": "gr",
      "thumb": "art/dot_gr_64"
    }
  ],
  "one": [
    {
      "id": "radiance",
      "design": "radiance",
      "price": "art",
      "engine": null,
      "wallOwn": {
        "base": "m/lounge_acrylic__eye__tight",
        "ratio": "4/5"
      }
    },
    {
      "id": "powder",
      "design": "powder",
      "price": "art",
      "engine": null
    },
    {
      "id": "universe",
      "design": "universe",
      "price": "art",
      "engine": null,
      "wallOwn": {
        "base": "m/lounge_acrylic__universe__tight",
        "ratio": "4/5"
      }
    },
    {
      "id": "gold",
      "design": "gold",
      "price": "art",
      "engine": "celestial_gold"
    },
    {
      "id": "splash",
      "design": "splash",
      "price": "art",
      "engine": null
    },
    {
      "id": "clean",
      "design": "clean",
      "price": "black",
      "engine": "studio_black"
    }
  ],
  "two": [
    {
      "id": "duo_infinity",
      "file": "duo_infinity_by",
      "price": "two",
      "src": "mixed",
      "engine": null,
      "wall": {
        "base": "m/lounge_acrylic_3x2__collision__tall",
        "ratio": "4/5"
      }
    },
    {
      "id": "duo_infinity_bb",
      "file": "duo_infinity_bb",
      "price": "two",
      "src": "mixed",
      "engine": null
    },
    {
      "id": "duo_infinity_uni",
      "file": "duo_infinity_bb_uni",
      "price": "two",
      "src": "mixed",
      "engine": null
    },
    {
      "id": "duo_kiss",
      "file": "duo_kiss_bb",
      "price": "two",
      "src": "mixed",
      "engine": null
    },
    {
      "id": "duo_clean",
      "file": "duo_clean_by",
      "price": "two",
      "src": "mixed",
      "engine": null
    }
  ],
  "family": [
    {
      "id": "fam_trio",
      "file": "fam_trio",
      "price": "n",
      "n": 3,
      "src": "mixed",
      "square": true,
      "engine": null
    },
    {
      "id": "fam_4",
      "file": "fam_4",
      "price": "n",
      "n": 4,
      "src": "mixed",
      "engine": null
    },
    {
      "id": "fam_5",
      "file": "fam_5",
      "price": "n",
      "n": 5,
      "src": "mixed",
      "engine": null
    },
    {
      "id": "fam_6",
      "file": "fam_6",
      "price": "n",
      "n": 6,
      "src": "mixed",
      "engine": null
    },
    {
      "id": "fam_6_uni",
      "file": "fam_6_uni",
      "price": "n",
      "n": 6,
      "src": "mixed",
      "engine": null
    }
  ]
};

/** "More ways to see it": the rooms that are not on the wall stage. */
export const MORE: readonly { id: string; base: AssetFamily }[] = [
  {
    "id": "hands",
    "base": "m/hands_acrylic__eye__tight"
  },
  {
    "id": "shelf",
    "base": "m/shelf_acrylic_30__eye__tight"
  },
  {
    "id": "hall",
    "base": "m/hall_acrylic_3x2__collision__tight"
  },
  {
    "id": "gallery",
    "base": "m/gallery_acrylic_oblique__collision__tight"
  }
];

/** The Reveal's eyes: two registered layers (photo, restored iris; 900 and 1200 px) and the artwork of the strip. */
export const REVEAL: { readonly eyes: readonly { id: 'gd' | 'br' | 'own'; photo: AssetFamily; iris: AssetFamily; art: AssetFile }[] } = {
  "eyes": [
    {
      "id": "gd",
      "photo": "reveal/gd_photo",
      "iris": "reveal/gd_iris",
      "art": "art/radiance_gd_900"
    },
    {
      "id": "br",
      "photo": "reveal/br_photo",
      "iris": "reveal/br_iris",
      "art": "art/radiance_br_900"
    },
    {
      "id": "own",
      "photo": "reveal/own_photo",
      "iris": "reveal/own_iris",
      "art": "art/radiance_own_900"
    }
  ]
};

/** The 96 px thumbnail of each wall artwork (the chips of the wall stage). */
export const WALL_THUMBS: Readonly<Record<WallArt, AssetFile>> = {
  "eye": "art/wallthumb_eye_96",
  "universe": "art/wallthumb_universe_96",
  "family4": "art/wallthumb_family4_96",
  "collision": "art/wallthumb_collision_96"
};

/** The close-up: a square of crop_px = [left, top, right, bottom] cut from the 4096 px file. */
export const FIBRE: { readonly crop_px: readonly [number, number, number, number]; readonly of: number } = {
  "crop_px": [
    2000,
    1000,
    3200,
    2200
  ],
  "of": 4096
};

/** The gallery tile -> the style id of api/_lib/iris.py that makes it today. The release gate (scripts/check_landing_assets.mjs)
 *  compares this with the styles the engine really has: a tile without one cannot be ordered yet. */
export const ENGINE_STYLE: Readonly<Record<string, string>> = {
  "gold": "celestial_gold",
  "clean": "studio_black"
};
