// GENERATED by scripts/build_landing_assets.py from scripts/landing_assets.json. Do not edit by hand: change the list and run
// the script (python scripts/build_landing_assets.py --src <folder of rendered pictures>).
//
// Every picture of the landing page has a content hash in its name (public/assets/landing/<dir>/<name>.<hash>.webp), so
// vercel.json serves it with "Cache-Control: immutable" for a year; a changed picture is another address. This file is the
// only place that knows the addresses: components ask for a name and get the address, the srcset and the size.
//
//   asset('m/lounge_acrylic__eye__tight')     the family: every width as a srcset, one of them as src (pick, default 900)
//   asset('reveal/gd_iris_900')               one file
//   asset('m/dining_metal__eye__wide', 2000)  the family with the 2000 px file as the src
//   asset('m/lounge_acrylic__eye__tight', { max: 1200 })   the family without its widest files
// A name that is not here does not compile. The structures that name pictures (wall, gallery, rooms, Reveal) are in
// ./assets.data.ts, which only the sections below the first screen load.

export const ASSET_BASE = '/assets/landing/';

/** name (folder and file name without the extension) -> [content hash, width, height, bytes] */
const FILES = {
  'art/clean_br_480': ['c3e2b2ea95', 480, 480, 14002],
  'art/clean_br_900': ['f0f4248f19', 900, 900, 37640],
  'art/clean_gr_480': ['b5cb554769', 480, 480, 12812],
  'art/clean_gr_900': ['9206cb13a8', 900, 900, 30104],
  'art/clean_own_480': ['08b9d35fa4', 480, 480, 11748],
  'art/clean_own_900': ['edbcbbf238', 900, 900, 28554],
  'art/clean_yg_480': ['0669c28bb6', 480, 480, 12942],
  'art/clean_yg_900': ['4ff7ba018c', 900, 900, 31194],
  'art/dot_br_64': ['cbf4413dc8', 64, 64, 1076],
  'art/dot_gr_64': ['f05426eb17', 64, 64, 1168],
  'art/dot_own_64': ['e1bb690f1b', 64, 64, 1224],
  'art/dot_yg_64': ['41adc7390e', 64, 64, 1178],
  'art/duo_clean_by_480': ['5b64181211', 480, 320, 11074],
  'art/duo_clean_by_900': ['55b51c8389', 900, 600, 30626],
  'art/duo_infinity_bb_480': ['7ccf7fc6e3', 480, 320, 15344],
  'art/duo_infinity_bb_900': ['3f12084cbb', 900, 600, 51316],
  'art/duo_infinity_bb_uni_480': ['b4435b1360', 480, 320, 17436],
  'art/duo_infinity_bb_uni_900': ['217022711e', 900, 600, 54420],
  'art/duo_infinity_by_480': ['14cf42ddd7', 480, 320, 16264],
  'art/duo_infinity_by_900': ['b87989201f', 900, 600, 51826],
  'art/duo_kiss_bb_480': ['30f216fa1e', 480, 320, 15070],
  'art/duo_kiss_bb_900': ['daced74f55', 900, 600, 48844],
  'art/fam_4_480': ['22389b4c22', 480, 320, 17088],
  'art/fam_4_900': ['61d5f1cf08', 900, 600, 57474],
  'art/fam_5_480': ['7210489a6f', 480, 320, 18756],
  'art/fam_5_900': ['4659b697da', 900, 600, 64408],
  'art/fam_6_480': ['7de12d6671', 480, 320, 19974],
  'art/fam_6_900': ['e38b0d5f60', 900, 600, 67010],
  'art/fam_6_uni_480': ['20dae73daa', 480, 320, 22344],
  'art/fam_6_uni_900': ['d34e0fd8b8', 900, 600, 71220],
  'art/fam_trio_480': ['9be32b883d', 480, 480, 26956],
  'art/fam_trio_900': ['1e0242059e', 900, 900, 83924],
  'art/fibre_crop_1200': ['8d939d25dc', 1200, 1200, 50710],
  'art/fibre_full_480': ['290123f8f0', 480, 480, 12812],
  'art/gold_br_480': ['aa5f8cc1d4', 480, 480, 21974],
  'art/gold_br_900': ['2b39ad48cb', 900, 900, 56860],
  'art/gold_gr_480': ['74ab07fc67', 480, 480, 20700],
  'art/gold_gr_900': ['4768520c48', 900, 900, 50870],
  'art/gold_own_480': ['30bf0c01d0', 480, 480, 20642],
  'art/gold_own_900': ['1cbe8238ab', 900, 900, 51020],
  'art/gold_yg_480': ['bf64749c08', 480, 480, 21744],
  'art/gold_yg_900': ['5326d6aa2d', 900, 900, 53968],
  'art/powder_br_480': ['c10108b8b2', 480, 480, 29880],
  'art/powder_br_900': ['db26aa96e2', 900, 900, 98684],
  'art/powder_gr_480': ['8e8c00c06c', 480, 480, 27782],
  'art/powder_gr_900': ['a9ad3fe6a9', 900, 900, 84066],
  'art/powder_own_480': ['71687e6105', 480, 480, 30706],
  'art/powder_own_900': ['75930f7c5c', 900, 900, 95482],
  'art/powder_yg_480': ['84be4b89be', 480, 480, 31984],
  'art/powder_yg_900': ['a9bbb50b70', 900, 900, 99844],
  'art/radiance_br_480': ['291966931b', 480, 480, 16182],
  'art/radiance_br_900': ['17c84f8dd1', 900, 900, 42968],
  'art/radiance_gd_900': ['5ce908d3d6', 900, 900, 38858],
  'art/radiance_gr_480': ['c8d7b6f04f', 480, 480, 16106],
  'art/radiance_gr_900': ['5ce908d3d6', 900, 900, 38858],
  'art/radiance_own_480': ['55aeed849f', 480, 480, 16760],
  'art/radiance_own_900': ['4475d3548f', 900, 900, 41994],
  'art/radiance_w03_900': ['4f11e0d9a1', 900, 900, 45500],
  'art/radiance_yg_480': ['1e1c150ab0', 480, 480, 17370],
  'art/radiance_yg_900': ['9a3085f203', 900, 900, 42692],
  'art/splash_br_480': ['e69a00db27', 480, 480, 26480],
  'art/splash_br_900': ['e8023b62c2', 900, 900, 74788],
  'art/splash_gr_480': ['2c16f660df', 480, 480, 19286],
  'art/splash_gr_900': ['60e3a8fba0', 900, 900, 48910],
  'art/splash_own_480': ['466d1ca298', 480, 480, 20312],
  'art/splash_own_900': ['2b445e7a07', 900, 900, 51402],
  'art/splash_yg_480': ['74af76e29f', 480, 480, 17648],
  'art/splash_yg_900': ['45783160e0', 900, 900, 42984],
  'art/universe_br_480': ['6d27e7b9ea', 480, 480, 17458],
  'art/universe_br_900': ['71788b86cc', 900, 900, 48346],
  'art/universe_gr_480': ['be75eaa5c3', 480, 480, 30032],
  'art/universe_gr_900': ['70f7d4c9ac', 900, 900, 76264],
  'art/universe_own_480': ['e58dc6d212', 480, 480, 29722],
  'art/universe_own_900': ['861a20d1b5', 900, 900, 77494],
  'art/universe_yg_480': ['9e6eae4505', 480, 480, 35306],
  'art/universe_yg_900': ['6556c01c62', 900, 900, 92698],
  'art/wallthumb_collision_96': ['577f8be9f7', 96, 96, 2840],
  'art/wallthumb_eye_96': ['1089ba3538', 96, 96, 1654],
  'art/wallthumb_family4_96': ['b339420893', 96, 96, 2536],
  'art/wallthumb_universe_96': ['08f5bfb7e9', 96, 96, 2270],
  'm/desk_block__eye__tight_1200': ['70fa279a58', 1200, 1499, 81882],
  'm/desk_block__eye__tight_600': ['f8cfc31ba4', 600, 750, 30416],
  'm/desk_block__family4__tight_1200': ['9c5d2af72b', 1200, 1499, 95834],
  'm/desk_block__family4__tight_600': ['8ab2075a38', 600, 750, 35712],
  'm/desk_block__universe__tight_1200': ['302ca59f7a', 1200, 1499, 85984],
  'm/desk_block__universe__tight_600': ['cf3ee43472', 600, 750, 32562],
  'm/dining_metal__eye__tight_1007': ['2b8179af59', 1007, 1259, 153664],
  'm/dining_metal__eye__tight_600': ['5e9168cbca', 600, 750, 27348],
  'm/dining_metal__eye__wide_1200': ['3adb599ab1', 1200, 805, 36922],
  'm/dining_metal__eye__wide_2000': ['310cc03b87', 2000, 1342, 169040],
  'm/dining_metal__family4__tight_1007': ['8b9675092c', 1007, 1259, 166128],
  'm/dining_metal__family4__tight_600': ['ddae0d9bf8', 600, 750, 31484],
  'm/dining_metal__universe__tight_1007': ['a094345d0c', 1007, 1259, 158446],
  'm/dining_metal__universe__tight_600': ['07ff510982', 600, 750, 29752],
  'm/gallery_acrylic_oblique__collision__tight_1200': ['c6621e89a7', 1200, 800, 66278],
  'm/gallery_acrylic_oblique__collision__tight_600': ['c8d4e963d3', 600, 400, 21730],
  'm/hall_acrylic_3x2__collision__tight_600': ['55599dc04e', 600, 400, 16518],
  'm/hall_acrylic_3x2__collision__tight_936': ['5064aeae0a', 936, 624, 47592],
  'm/hands_acrylic__eye__tight_1200': ['c04a05d893', 1200, 1500, 113774],
  'm/hands_acrylic__eye__tight_600': ['acae7dc782', 600, 750, 44924],
  'm/living_canvas__eye__tight_600': ['399ad82367', 600, 750, 15414],
  'm/living_canvas__eye__tight_842': ['8c1b067e3e', 842, 1052, 45298],
  'm/living_canvas__family4__tight_600': ['d06bb20a68', 600, 750, 18784],
  'm/living_canvas__family4__tight_842': ['651690933e', 842, 1052, 51966],
  'm/living_canvas__universe__tight_600': ['ae6060d568', 600, 750, 17574],
  'm/living_canvas__universe__tight_842': ['b4c82e3f22', 842, 1052, 47816],
  'm/lounge_acrylic_3x2__collision__tall_1200': ['d64119a778', 1200, 1500, 114386],
  'm/lounge_acrylic_3x2__collision__tall_600': ['f48429479c', 600, 750, 33056],
  'm/lounge_acrylic__eye__tight_1200': ['b33a0bade1', 1200, 1500, 99854],
  'm/lounge_acrylic__eye__tight_2000': ['2e425d0407', 2000, 2500, 267548],
  'm/lounge_acrylic__eye__tight_600': ['0a46ec5ab4', 600, 750, 23970],
  'm/lounge_acrylic__eye__tight_900': ['6894632aca', 900, 1125, 38534],
  'm/lounge_acrylic__family4__tight_1200': ['0186330806', 1200, 1500, 114110],
  'm/lounge_acrylic__family4__tight_2000': ['dd9ce81e50', 2000, 2500, 301934],
  'm/lounge_acrylic__family4__tight_600': ['c8a8a3ed6c', 600, 750, 28524],
  'm/lounge_acrylic__universe__tight_1200': ['03e6ebe079', 1200, 1500, 104552],
  'm/lounge_acrylic__universe__tight_600': ['0a166b39ef', 600, 750, 26794],
  'm/lounge_canvas_3x2__collision__tall_1200': ['3fa8431313', 1200, 1500, 115134],
  'm/lounge_canvas_3x2__collision__tall_600': ['0713b24265', 600, 750, 33538],
  'm/lounge_framed_3x2__collision__tall_1200': ['850b0f2ecd', 1200, 1500, 80868],
  'm/lounge_framed_3x2__collision__tall_600': ['e9d0b9b80c', 600, 750, 22192],
  'm/lounge_framed__eye__tight_1200': ['6d37112464', 1200, 1500, 79180],
  'm/lounge_framed__eye__tight_600': ['a88b3d9487', 600, 750, 19622],
  'm/lounge_framed__family4__tight_1200': ['81c6ecff30', 1200, 1500, 90732],
  'm/lounge_framed__family4__tight_600': ['d7454fc800', 600, 750, 23292],
  'm/lounge_framed__universe__tight_1200': ['2f88eea23b', 1200, 1500, 82838],
  'm/lounge_framed__universe__tight_600': ['485037daa3', 600, 750, 23382],
  'm/lounge_metal_3x2__collision__tall_1200': ['f8daae153d', 1200, 1500, 131784],
  'm/lounge_metal_3x2__collision__tall_600': ['0fd2806826', 600, 750, 35824],
  'm/macro_acrylic_corner__universe__wide_1200': ['484b181447', 1200, 805, 26050],
  'm/macro_acrylic_corner__universe__wide_2000': ['7c34f0a746', 2000, 1342, 55680],
  'm/macro_acrylic_corner__universe__wide_600': ['96b973cf76', 600, 403, 10506],
  'm/phone_desk__collision__wide_1200': ['b8fa6dc7a9', 1200, 1490, 100652],
  'm/phone_desk__collision__wide_2000': ['4ca0f843b0', 2000, 2483, 220632],
  'm/phone_desk__collision__wide_600': ['f9c22f0a59', 600, 745, 37822],
  'm/phone_desk__eye__wide_1200': ['49ae669f14', 1200, 1490, 103926],
  'm/phone_desk__eye__wide_2000': ['40930072fe', 2000, 2483, 228518],
  'm/phone_desk__eye__wide_600': ['54bb15a5bf', 600, 745, 38870],
  'm/phone_desk__eye_de__wide_1200': ['46e971ecd8', 1200, 1490, 105498],
  'm/phone_desk__eye_de__wide_2000': ['ac860562e7', 2000, 2483, 229100],
  'm/phone_desk__eye_de__wide_600': ['8b24c9b640', 600, 745, 38924],
  'm/phone_desk__family4__wide_1200': ['6b687f539a', 1200, 1490, 106382],
  'm/phone_desk__family4__wide_2000': ['04e7dab815', 2000, 2483, 230358],
  'm/phone_desk__family4__wide_600': ['9e6b47a4aa', 600, 745, 38830],
  'm/phone_desk__universe__wide_1200': ['182dfda0e1', 1200, 1490, 112756],
  'm/phone_desk__universe__wide_2000': ['b758849bc3', 2000, 2483, 240096],
  'm/phone_desk__universe__wide_600': ['c24b88f2da', 600, 745, 41654],
  'm/shelf_acrylic_30__eye__tight_600': ['3b092852f2', 600, 751, 21630],
  'm/shelf_acrylic_30__eye__tight_881': ['45a4f67e6d', 881, 1102, 55024],
  'reveal/br_iris_1200': ['3aa10094f4', 1200, 1200, 55958],
  'reveal/br_iris_900': ['90036675cd', 900, 900, 38430],
  'reveal/br_photo_1200': ['d778ba6438', 1200, 1200, 62486],
  'reveal/br_photo_900': ['cdeaeb3734', 900, 900, 46036],
  'reveal/disc_own_420': ['03cc37b24d', 420, 420, 13790],
  'reveal/gd_iris_1200': ['de76750d8f', 1200, 1200, 44918],
  'reveal/gd_iris_900': ['bf686d6084', 900, 900, 31966],
  'reveal/gd_photo_1200': ['7ffbe423ec', 1200, 1200, 46912],
  'reveal/gd_photo_900': ['b220424270', 900, 900, 33510],
  'reveal/own_iris_1200': ['8d2d4ea10b', 1200, 1200, 60480],
  'reveal/own_iris_900': ['10a1f28561', 900, 900, 42908],
  'reveal/own_photo_1200': ['223e7344d1', 1200, 1200, 32944],
  'reveal/own_photo_900': ['1e639a177d', 900, 900, 23992],
  'ui/before-phone-crop-315': ['992b984c9f', 315, 315, 13726],
  'ui/preview_wm_360': ['b110867a99', 360, 360, 18260],
} as const satisfies Record<string, readonly [string, number, number, number]>;

/** family (the name without _<width>) -> the widths that exist, ascending */
const WIDTHS = {
  'art/clean_br': [480, 900],
  'art/clean_gr': [480, 900],
  'art/clean_own': [480, 900],
  'art/clean_yg': [480, 900],
  'art/dot_br': [64],
  'art/dot_gr': [64],
  'art/dot_own': [64],
  'art/dot_yg': [64],
  'art/duo_clean_by': [480, 900],
  'art/duo_infinity_bb': [480, 900],
  'art/duo_infinity_bb_uni': [480, 900],
  'art/duo_infinity_by': [480, 900],
  'art/duo_kiss_bb': [480, 900],
  'art/fam_4': [480, 900],
  'art/fam_5': [480, 900],
  'art/fam_6': [480, 900],
  'art/fam_6_uni': [480, 900],
  'art/fam_trio': [480, 900],
  'art/fibre_crop': [1200],
  'art/fibre_full': [480],
  'art/gold_br': [480, 900],
  'art/gold_gr': [480, 900],
  'art/gold_own': [480, 900],
  'art/gold_yg': [480, 900],
  'art/powder_br': [480, 900],
  'art/powder_gr': [480, 900],
  'art/powder_own': [480, 900],
  'art/powder_yg': [480, 900],
  'art/radiance_br': [480, 900],
  'art/radiance_gd': [900],
  'art/radiance_gr': [480, 900],
  'art/radiance_own': [480, 900],
  'art/radiance_w03': [900],
  'art/radiance_yg': [480, 900],
  'art/splash_br': [480, 900],
  'art/splash_gr': [480, 900],
  'art/splash_own': [480, 900],
  'art/splash_yg': [480, 900],
  'art/universe_br': [480, 900],
  'art/universe_gr': [480, 900],
  'art/universe_own': [480, 900],
  'art/universe_yg': [480, 900],
  'art/wallthumb_collision': [96],
  'art/wallthumb_eye': [96],
  'art/wallthumb_family4': [96],
  'art/wallthumb_universe': [96],
  'm/desk_block__eye__tight': [600, 1200],
  'm/desk_block__family4__tight': [600, 1200],
  'm/desk_block__universe__tight': [600, 1200],
  'm/dining_metal__eye__tight': [600, 1007],
  'm/dining_metal__eye__wide': [1200, 2000],
  'm/dining_metal__family4__tight': [600, 1007],
  'm/dining_metal__universe__tight': [600, 1007],
  'm/gallery_acrylic_oblique__collision__tight': [600, 1200],
  'm/hall_acrylic_3x2__collision__tight': [600, 936],
  'm/hands_acrylic__eye__tight': [600, 1200],
  'm/living_canvas__eye__tight': [600, 842],
  'm/living_canvas__family4__tight': [600, 842],
  'm/living_canvas__universe__tight': [600, 842],
  'm/lounge_acrylic_3x2__collision__tall': [600, 1200],
  'm/lounge_acrylic__eye__tight': [600, 900, 1200, 2000],
  'm/lounge_acrylic__family4__tight': [600, 1200, 2000],
  'm/lounge_acrylic__universe__tight': [600, 1200],
  'm/lounge_canvas_3x2__collision__tall': [600, 1200],
  'm/lounge_framed_3x2__collision__tall': [600, 1200],
  'm/lounge_framed__eye__tight': [600, 1200],
  'm/lounge_framed__family4__tight': [600, 1200],
  'm/lounge_framed__universe__tight': [600, 1200],
  'm/lounge_metal_3x2__collision__tall': [600, 1200],
  'm/macro_acrylic_corner__universe__wide': [600, 1200, 2000],
  'm/phone_desk__collision__wide': [600, 1200, 2000],
  'm/phone_desk__eye__wide': [600, 1200, 2000],
  'm/phone_desk__eye_de__wide': [600, 1200, 2000],
  'm/phone_desk__family4__wide': [600, 1200, 2000],
  'm/phone_desk__universe__wide': [600, 1200, 2000],
  'm/shelf_acrylic_30__eye__tight': [600, 881],
  'reveal/br_iris': [900, 1200],
  'reveal/br_photo': [900, 1200],
  'reveal/disc_own': [420],
  'reveal/gd_iris': [900, 1200],
  'reveal/gd_photo': [900, 1200],
  'reveal/own_iris': [900, 1200],
  'reveal/own_photo': [900, 1200],
  'ui/preview_wm': [360],
} as const satisfies Record<string, readonly number[]>;

export type AssetFile = keyof typeof FILES;
export type AssetFamily = keyof typeof WIDTHS;
export type AssetName = AssetFile | AssetFamily;

/** What a picture needs: the address, the srcset of a family with several widths, the size of the src (every width of a
 *  family has the same shape, so width and height reserve the right space). Same shape as PictureAsset in ./ui.tsx. */
export interface PictureAsset { src: string; srcset?: string; w: number; h: number }

/** The address of one file. */
export function assetUrl(file: AssetFile): string {
  const slash = file.lastIndexOf('/');
  return `${ASSET_BASE}${file.slice(0, slash + 1)}${file.slice(slash + 1)}.${FILES[file][0]}.webp`;
}

/** The widths a family has, ascending. */
export function assetWidths(family: AssetFamily): readonly number[] {
  return WIDTHS[family];
}

/** How a family becomes a srcset: pick = the width whose file is the src (nearest to it, default 900); max = the widest file the
 *  srcset offers (the first screen offers 600, 900 and 1200 only, so a phone with a dense screen does not fetch the 2000 px file). */
export type AssetOptions = number | { pick?: number; max?: number };

/** A file by name, or a family as a srcset. */
export function asset(name: AssetName, options: AssetOptions = {}): PictureAsset {
  if (name in FILES) {
    const f = name as AssetFile;
    return { src: assetUrl(f), w: FILES[f][1], h: FILES[f][2] };
  }
  const o = typeof options === 'number' ? { pick: options } : options;
  const pick = o.pick ?? 900;
  const all = WIDTHS[name as AssetFamily];
  const ws = all.filter((w) => w <= (o.max ?? Infinity));
  if (ws.length === 0) throw new Error(`asset ${name}: no file up to ${o.max} px`);
  let best: number = ws[0];
  for (const w of ws) if (Math.abs(w - pick) < Math.abs(best - pick)) best = w;
  const file = (w: number) => `${name}_${w}` as AssetFile;
  return {
    src: assetUrl(file(best)),
    srcset: ws.length > 1 ? ws.map((w) => `${assetUrl(file(w))} ${w}w`).join(', ') : undefined,
    w: FILES[file(best)][1],
    h: FILES[file(best)][2],
  };
}

/** Every address of the manifest (the build's check and the service of the preload list read it). */
export const ALL_ASSET_FILES = Object.keys(FILES) as AssetFile[];
export const ASSET_HASH = FILES as Readonly<Record<AssetFile, readonly [string, number, number, number]>>;
