// GENERATED by scripts/bake_name_chars.py from the artwork font (api/_assets/fonts/Cinzel.ttf, read by api/_lib/styles/text.py font_cover): do not edit.
// The code points the font draws, as inclusive ranges. The customer's names, date and family name are set in capitals in that font, so a letter
// outside these ranges (after upper-casing) would print as an empty box in the delivered file: src/try/names.ts refuses it before checkout.
// The suite v3picker runs `python scripts/bake_name_chars.py --check` and compares the page's reading with the server's for every code point.
// 367 code points in 52 ranges.
export const NAME_FONT_RANGES: readonly (readonly [number, number])[] = [
  [32, 126], [160, 263], [266, 275], [278, 283], [286, 291], [294, 295],
  [298, 299], [302, 307], [310, 311], [313, 328], [330, 333], [336, 347],
  [350, 359], [362, 363], [366, 382], [402, 402], [536, 539], [710, 711],
  [728, 733], [768, 772], [774, 776], [778, 780], [806, 808], [916, 916],
  [937, 937], [956, 956], [960, 960], [7808, 7813], [7922, 7923], [8211, 8212],
  [8216, 8218], [8220, 8222], [8224, 8226], [8230, 8230], [8240, 8240], [8249, 8250],
  [8260, 8260], [8308, 8308], [8364, 8364], [8482, 8482], [8706, 8706], [8719, 8719],
  [8721, 8722], [8725, 8725], [8730, 8730], [8734, 8734], [8747, 8747], [8776, 8776],
  [8800, 8800], [8804, 8805], [9674, 9674], [64257, 64258],
];
