# -*- coding: utf-8 -*-
"""Offline tool (never in a function): bakes src/try/nameChars.ts, the letters the artwork font can draw, for the page.

    python scripts/bake_name_chars.py [--write | --check]

The customer's names, date and family name are drawn in the artwork font (api/_lib/styles/text.py, Cinzel capitals); a letter that font has no
glyph for would print as an empty box in a delivered file. The server knows the font's own cmap (text.font_cover); the page has to refuse such a
letter BEFORE checkout, so it carries the same list as ranges of code points. Without a flag the file's text is printed; --write rewrites
src/try/nameChars.ts; --check exits 1 when the file on disk is not what the font says (the suite v3picker runs it, so a font that changes can
never leave the page with a stale list).
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
OUT = os.path.join(ROOT, "src", "try", "nameChars.ts")
sys.path.insert(0, os.path.join(ROOT, "api"))


def ranges(codes):
    out, start, prev = [], None, None
    for c in sorted(codes):
        if start is None:
            start = prev = c
        elif c == prev + 1:
            prev = c
        else:
            out.append((start, prev))
            start = prev = c
    if start is not None:
        out.append((start, prev))
    return out


def render():
    from _lib.styles import text as TX
    cover = TX.font_cover("Cinzel.ttf")
    rows = ranges(cover)
    lines, row = [], []
    for a, b in rows:
        row.append(f"[{a}, {b}]")
        if len(row) == 6:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    return (
        "// GENERATED by scripts/bake_name_chars.py from the artwork font (api/_assets/fonts/Cinzel.ttf, read by api/_lib/styles/text.py font_cover): do not edit.\n"
        "// The code points the font draws, as inclusive ranges. The customer's names, date and family name are set in capitals in that font, so a letter\n"
        "// outside these ranges (after upper-casing) would print as an empty box in the delivered file: src/try/names.ts refuses it before checkout.\n"
        "// The suite v3picker runs `python scripts/bake_name_chars.py --check` and compares the page's reading with the server's for every code point.\n"
        f"// {len(cover)} code points in {len(rows)} ranges.\n"
        "export const NAME_FONT_RANGES: readonly (readonly [number, number])[] = [\n" + "\n".join(lines) + "\n];\n"
    )


def main(argv):
    text = render()
    if "--write" in argv:
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote", os.path.relpath(OUT, ROOT))
        return 0
    if "--check" in argv:
        try:
            with open(OUT, encoding="utf-8", newline="") as f:
                disk = f.read().replace("\r\n", "\n")
        except OSError:
            print("src/try/nameChars.ts is missing: run python scripts/bake_name_chars.py --write")
            return 1
        if disk != text:
            print("src/try/nameChars.ts is not what the artwork font says: run python scripts/bake_name_chars.py --write")
            return 1
        print("src/try/nameChars.ts matches the artwork font")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
